### ISSUE TITLE
Improve tabs.js

### ISSUE THREAD

**Issue by Cleecanth** [UWHealth/Front-End-Framework#5]
Currently the tabs.js is built like a single function entity. 

- [ ] Make tab formatting scoped. Once it's called, all tab groups get formatted, but the init script implies that only a specified group of tabs will get style.
- [ ] Modularize events and formatting. Currently formatting is done in the same function as event handling. This is convenient for making sure click handlers are bound after the document loads, but it ruins the readability of the code.
- [ ] Modularize events. The events are spaghetti-code to the max. Need to generalize and make more flexible so it's easier to add enhancements down the road.

**Comment by cdthorpe** [comment]
Allow for tabs to be referenced & initialized via URL path
